---
# Mainly from: https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
- hosts: newservers
  vars:
  - ubuntu_release: trusty
  - logwatch_email: prueba@algunmail.com
  - deploy_password: '$6$AC3bdCF7!$6CkgcL7DZ3Gg'
    # crypted password, generated on a Linux box using: echo 'import crypt,getpass; print crypt.crypt(getpass.getpass(), "$6$AC3bdCF7!")' | python -

  tasks:
  - name: Update APT package cache
    apt: update_cache=yes

  - name: Run apt-get upgrade
    apt: upgrade=yes

  - name: Add deployment user
    user: name=deploy password=$deploy_password shell=/bin/bash

  - name: Add authorized deploy key for Deploy user
    authorized_key: user=deploy key="{{ lookup('file', 'key')}}"

  - name: Add github key
    copy: src=key_github dest=/home/deploy/.ssh/id_rsa mode=700 owner=deploy

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify: Restart ssh

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart ssh

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=present

  - name: Adjust APT update intervals
    copy: src=config/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  - name: Install dependencies
    apt: name={{ item }} state=installed update-cache=yes
    with_items:
      - autoconf
      - automake
      - bison
      - build-essential
      - curl
      - dialog
      - exuberant-ctags
      - git-core
      - git-svn
      - libcurl4-openssl-dev
      - libreadline6
      - libreadline6-dev
      - libreadline-dev
      - libsqlite3-0
      - libsqlite3-dev
      - libssl-dev
      - libyaml-dev
      - libc6-dev
      - libncurses5-dev
      - libtool
      - libxml2-dev
      - libxslt1-dev
      - openssl
      - python-software-properties
      - sqlite3
      - subversion
      - zlib1g
      - zlib1g-dev

  - name: Ensure www bash dir exists
    file: dest=/var/www state=directory owner=deploy group=deploy

  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted
